FLOWER_NAME_KO_MAP = {
    "alstroemeria": "알스트로메리아",
    "amaryllis": "아마릴리스",
    "anthurium": "안스리움",
    "azalea": "철쭉",
    "bee_balm": "베르가못",
    "bellflower": "초롱꽃",
    "blackberry_lily": "범부채",
    "blanket_flower": "천인국",
    "bougainvillea": "부겐빌레아",
    "bromeliad": "브로멜리아드",
    "calla_lily": "카라",
    "camellia": "동백",
    "canna_lily": "칸나",
    "canterbury_bells": "캔터베리벨",
    "cape_flower": "케이프플라워",
    "carnation": "카네이션",
    "cattleya": "카틀레야",
    "celosia": "맨드라미",
    "chamomile": "캐모마일",
    "chrysanthemum": "국화",
    "clematis": "클레마티스",
    "columbine": "매발톱꽃",
    "coneflower": "에키네시아",
    "cosmos": "코스모스",
    "cyclamen": "시클라멘",
    "daffodil": "수선화",
    "dahlia": "달리아",
    "daisy": "데이지",
    "desert_rose": "석화",
    "doraji": "도라지꽃",
    "eryngo": "에린지움",
    "feather_celosia": "깃털맨드라미",
    "foxglove": "디기탈리스",
    "freesia": "프리지아",
    "fritillaria": "프리틸라리아",
    "garden_phlox": "풀협죽도",
    "gaura": "가우라",
    "gazania": "가자니아",
    "gentian": "용담",
    "geranium": "제라늄",
    "gerbera": "거베라",
    "gladiolus": "글라디올러스",
    "globe_thistle": "에키놉스",
    "gloriosa_lily": "글로리오사",
    "gyeongyeopduran": "겹엽두란",
    "gypsophila": "안개꽃",
    "hellebores": "헬레보어",
    "hibiscus": "무궁화",
    "hyacinth": "히아신스",
    "hydrangea": "수국",
    "iris": "아이리스",
    "ixora": "익소라",
    "japanese_anemone": "추명국",
    "kalanchoe": "칼랑코에",
    "lily": "백합",
    "lisianthus": "리시안셔스",
    "magnolia": "목련",
    "marigold": "메리골드",
    "masterwort": "마스터워트",
    "mexican_petunia": "멕시칸 페튜니아",
    "monkshood": "투구꽃",
    "morning_glory": "나팔꽃",
    "mulmangcho": "물망초",
    "nasturtium": "한련화",
    "nigella": "니겔라",
    "orchid": "난초",
    "osteospermum": "오스테오스퍼멈",
    "pansy": "팬지",
    "passion_flower": "시계꽃",
    "peony": "작약",
    "petunia": "페튜니아",
    "pincushion_flower": "스카비오사",
    "pink_primrose": "분홍달맞이꽃",
    "plumeria": "플루메리아",
    "poinsettia": "포인세티아",
    "poppy": "양귀비",
    "primula": "프리뮬라",
    "red_ginger": "레드진저",
    "rose": "장미",
    "sampaguita": "삼파귀타",
    "silverbush": "실버부시",
    "spring_crocus": "봄크로커스",
    "stock": "스토크",
    "sunflower": "해바라기",
    "sweet_pea": "스위트피",
    "sweet_william": "패랭이꽃",
    "trumpet_creeper": "능소화",
    "tulip": "튤립",
    "wallflower": "월플라워",
}


BOUQUET_RECOMMENDABLE_FLOWER_KEYS = {
    "alstroemeria",
    "amaryllis",
    "anthurium",
    "calla_lily",
    "carnation",
    "cattleya",
    "celosia",
    "chamomile",
    "chrysanthemum",
    "cosmos",
    "daffodil",
    "dahlia",
    "daisy",
    "freesia",
    "gerbera",
    "gladiolus",
    "gypsophila",
    "hyacinth",
    "hydrangea",
    "iris",
    "lily",
    "lisianthus",
    "orchid",
    "peony",
    "rose",
    "stock",
    "sunflower",
    "sweet_pea",
    "tulip",
}